[package]
name = "tdw-provider-finra"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[features]
default = []
http = ["dep:async-trait","dep:bytes","dep:reqwest","dep:tdw-core","dep:tdw-domain","dep:tokio"]

[dependencies]
async-trait = { workspace = true, optional = true }
bytes = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tdw-core = { workspace = true, optional = true }
tdw-domain = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true }

[lints]
workspace = true
