[package]
name = "tdw-worker"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[features]
default = []
postgres = ["sqlx/postgres"]

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tdw-protocol = { workspace = true }
tdw-service-api = { path = "../tdw-service-api" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time", "signal"] }

[lints]
workspace = true
