[package]
name = "tdw-storage-qdrant"
version = "0.1.0"
edition = "2024"
publish = false
license = "UNLICENSED"

[dependencies]
async-trait = { workspace = true }
tdw-core = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
