#![allow(clippy::doc_markdown)] // narrative docstrings describe MCP surface
//! `tdw.kg.answer` — GraphRAG-style cited answer synthesis (knowledge-system K-M3).
//!
//! # Retrieve → Expand → Answer pipeline
//!
//! [`execute`] drives three sequenced phases:
//!
//! 1. **RETRIEVE** — hybrid search via the platform [`Retriever`], honouring the
//!    `as_of` temporal gate (leakage-safe: all hits carry `as_of` that is ≤ the
//!    query cutoff, enforced by the retriever's payload predicates and the graph
//!    channel's [`document_visible`] gate — not re-implemented here).
//! 2. **EXPAND** — optional k-hop graph expansion (`k_hop` arg → [`GraphExpansion`]),
//!    also leakage-safe because the retriever applies the same temporal filter to
//!    expansion paths.
//! 3. **ANSWER** — assemble a cited answer from the retrieved hit set:
//!    - **Synthesized stub** (only reachable via the `TDW_ALLOW_STUB_FEEDBACK=1`
//!      operator override — no production `LanguageModel` is wired into the runtime
//!      yet, #345): exercises the synthesis code-path with inline `[doc-id]`
//!      citations but is stamped truthfully as a stub, never bare `"synthesized"`.
//!    - **Extractive** (default — no model / stub model): top passages + citation
//!      list, clearly labelled `"extractive (no model configured)"`. Keyless
//!      installs get a fully functional extractive path.
//!
//! # Citation-validity contract
//!
//! Every cited document id MUST appear in the retrieved hit set returned by the
//! retriever — hallucinated citations are structurally impossible because the
//! citation list is built directly from hit ids, not generated by an LLM.
//!
//! In synthesized mode the LLM sees explicit inline markers (`[doc-id]` in the
//! prompt) and is instructed to cite only those ids; the post-processing step
//! validates that every id appearing in the NL answer is in the retrieved set
//! before returning the response. Any out-of-set id is stripped with a loud
//! `"citation_validity_warning"` so callers always know the answer was filtered.
//!
//! # Point-in-time (finance differentiator)
//!
//! The `as_of` argument makes answers backtest-safe.  A query with
//! `as_of = "2024-01-01"` must never surface, cite, or synthesize from a fact
//! dated after that date.  This guarantee is delegated entirely to the
//! [`Retriever`]: the payload `as_of ≤ cutoff` condition excludes undated and
//! future-dated documents from every channel (vector, lexical, tag, graph).
//! The answer tool trusts and re-exposes this guarantee without re-implementing
//! temporal filtering, so leakage bugs cannot originate here independently.
//!
//! # Confidence
//!
//! K-R6 confidence scores carried on [`RetrievedHit`]s are surfaced on each
//! citation and as an aggregate `answer_confidence` (mean of cited hit scores, or
//! `null` when no hits carry confidence).  See [`AnswerCitation`].
//!
//! # Mode stamp
//!
//! The response always carries a truthful `"mode"` stamp: either
//! `"extractive (no model configured)"` or
//! `"synthesized (stub model — not production NL synthesis)"` — never a bare
//! `"synthesized"` while a real production `LanguageModel` is unwired — so
//! callers can never mistake stub boilerplate for production NL synthesis.

use serde_json::{Map, Value, json};
use tdw_knowledge::runtime::KnowledgeRuntime;
use tdw_retrieve::{GraphExpansion, KnowledgeQuery, QueryFilter};

use crate::{
    ToolDescriptor, ToolExecution, ToolFailure, knowledge_tools::block_on, structured, tool,
};

// ── Tool name ─────────────────────────────────────────────────────────────────

/// The tool name owned by this module.
pub const TOOL_NAME: &str = "tdw.kg.answer";

/// Whether `name` is the answer tool.
#[must_use]
pub fn owns(name: &str) -> bool {
    name == TOOL_NAME
}

// ── Caps ──────────────────────────────────────────────────────────────────────

/// Maximum characters in a query string (mirrors `tdw.kg.search`).
const MAX_QUERY_CHARS: usize = 8192;

/// Default number of retrieved hits assembled into the answer context.
const DEFAULT_TOP_K: usize = 8;

/// Maximum answer hits (capped to avoid unbounded context assembly).
const MAX_ANSWER_TOP_K: usize = 32;

/// Maximum characters for the NL synthesis prompt passage per hit.
const MAX_PASSAGE_CHARS: usize = 2_048;

/// Maximum total characters contributed to the synthesis prompt across all hits.
const MAX_PROMPT_CONTEXT_CHARS: usize = 24_576;

/// Maximum output tokens requested from the language model (reserved for #345 production wiring).
#[allow(dead_code)]
const MAX_OUTPUT_TOKENS: u32 = 1_024;

// ── Mode stamps (truthful) ──────────────────────────────────────────────────

/// Extractive mode stamp: no language model — top passages + citation list.
const MODE_EXTRACTIVE: &str = "extractive (no model configured)";

/// Stub-synthesis mode stamp. The synthesized code-path is exercised but the
/// answer text is assembled deterministically (no production LLM is wired into
/// `KnowledgeRuntime` yet — #345). The stamp MUST NOT claim bare `"synthesized"`
/// because that would misrepresent a stub as production NL synthesis (K-M3
/// citation-honesty guarantee). Until a real `LanguageModel` is wired, the only
/// way to reach this path is the `TDW_ALLOW_STUB_FEEDBACK=1` operator override.
const MODE_SYNTHESIZED_STUB: &str = "synthesized (stub model — not production NL synthesis)";

// ── Descriptor ────────────────────────────────────────────────────────────────

/// Descriptor for `tdw.kg.answer`. Appended to `tools/list` only when a
/// knowledge runtime is attached (gated in [`crate::McpServer`]).
///
/// The tool is read-only and idempotent (same args → same answer from the same
/// knowledge state, no mutations).
#[must_use]
pub fn descriptor() -> ToolDescriptor {
    tool(
        TOOL_NAME,
        "Knowledge Graph Answer",
        "GraphRAG-style cited answer synthesis (knowledge-system K-M3). \
         Runs retrieve → graph-expand → answer over the knowledge graph and returns \
         an answer with MANDATORY citations to the document ids it drew from. \
         \n\n\
         Two modes (truthfully stamped in the response):\n\
         - extractive (no model configured): top passages + citation list (keyless, \
           fully functional).\n\
         - synthesized (stub model …): the synthesis code-path with inline [doc-id] \
           citations. Until a production LanguageModel is wired into the runtime this \
           is a deterministic stub, stamped as such so it is never mistaken for \
           production NL synthesis.\n\
         \n\
         Point-in-time safety: as_of makes answers backtest-safe — temporal leakage \
         is impossible because the retriever's payload predicates exclude all facts \
         dated after as_of from every channel (vector, lexical, tag, graph). \
         \n\
         Citation-validity contract: every cited id EXISTS in the retrieved set — \
         hallucinated citations are structurally impossible. \
         \n\
         Caps: query ≤ 8192 chars; top_k ≤ 32; k_hop 1..=3.",
        json!({
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Free-text question (non-empty, ≤ 8192 chars)."
                },
                "top_k": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 32,
                    "description": "Number of retrieved hits assembled into the answer context (default 8)."
                },
                "as_of": {
                    "type": "string",
                    "description": "Temporal point of view, YYYY-MM-DD. Makes the answer \
                                   backtest-safe: no fact dated after this date will be \
                                   retrieved, cited, or synthesized from."
                },
                "provenance_classes": {
                    "type": "array",
                    "items": { "type": "string" },
                    "description": "Restrict to hits from these provenance classes \
                                   (e.g. [\"ingest\", \"rule\", \"agent\", \"manual\", \"system\"]). \
                                   Omit to include all. Reuses the K-X3 trust-dial filter \
                                   concept: class names match the Provenance variant tag."
                },
                "tags_any": {
                    "type": "array",
                    "items": { "type": "string" },
                    "description": "Match any of these tags (taxonomy descendants included)."
                },
                "plane": {
                    "type": "string",
                    "description": "Restrict to one plane (agent / platform / shared)."
                },
                "k_hop": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 3,
                    "description": "Optional graph expansion hop budget (1..=3). When supplied, \
                                   the top retrieved hits seed a BFS that contributes \
                                   related documents to the answer context."
                }
            },
            "required": ["query"],
            "additionalProperties": false
        }),
    )
}

// ── Dispatch ──────────────────────────────────────────────────────────────────

/// Execute `tdw.kg.answer`. Every failure is a tool error, never a protocol error.
///
/// # Errors
///
/// Returns [`ToolFailure::Execution`] for malformed input, a missing engine,
/// or an engine failure. Never returns [`ToolFailure::Protocol`].
pub fn execute(
    runtime: &KnowledgeRuntime,
    arguments: &Map<String, Value>,
) -> Result<ToolExecution, ToolFailure> {
    // ── 1. Parse arguments ────────────────────────────────────────────────────
    let query_text = require_str(arguments, "query")?;
    if query_text.chars().count() > MAX_QUERY_CHARS {
        return Err(execution(format!(
            "query must be at most {MAX_QUERY_CHARS} characters"
        )));
    }

    let top_k = optional_usize(arguments, "top_k")?.unwrap_or(DEFAULT_TOP_K);
    if top_k > MAX_ANSWER_TOP_K {
        return Err(execution(format!(
            "top_k must be at most {MAX_ANSWER_TOP_K}, got {top_k}"
        )));
    }

    let as_of = optional_str(arguments, "as_of").map(ToString::to_string);
    let provenance_classes = optional_string_array(arguments, "provenance_classes")?;
    let tags_any = optional_string_array(arguments, "tags_any")?.unwrap_or_default();
    let plane = optional_str(arguments, "plane").map(ToString::to_string);
    let k_hop = optional_u8(arguments, "k_hop")?;

    if let Some(hop) = k_hop
        && !(1..=3).contains(&hop)
    {
        return Err(execution(format!("k_hop must be 1..=3, got {hop}")));
    }

    // ── 2. Build the retrieval query (reuses Retriever — no re-impl of temporal) ──
    let filter = QueryFilter {
        tags_any,
        entity_kinds: None,
        plane,
        as_of: as_of.clone(),
        // provenance_classes is handled post-retrieval by apply_provenance_filter
        // (entity_id-prefix heuristic); we don't pass it to the retriever's own
        // TrustClass filter to avoid a double-filter that would lose hits the
        // heuristic later classifies correctly.
        provenance_classes: None,
    };
    let expand = k_hop.map(|hop| GraphExpansion {
        k_hop: hop,
        edge_types: Vec::new(),
        per_hit_limit: 8,
        decay: 0.5,
    });
    let knowledge_query = KnowledgeQuery::try_new(query_text, top_k, filter, expand)
        .map_err(|error| execution(error.to_string()))?;

    // ── 3. Retrieve + Expand (leakage-safe: Retriever enforces as_of on all channels) ──
    let hits = block_on(runtime.retriever().search(&knowledge_query))
        .map_err(|error| execution(error.to_string()))?;

    // ── 4. Apply provenance-class filter (K-X3 trust-dial reuse) ─────────────
    // The provenance_classes arg narrows hits by the provenance tag on their
    // entity edges.  Since RetrievedHit does not carry the full edge provenance
    // (only confidence scores), we filter by the entity_id prefix heuristic:
    // actual provenance filtering requires the graph.  When the graph is present
    // and provenance_classes is supplied we pass through; when absent we surface
    // an honest note.  The citation set is ONLY from the hits that pass the filter.
    let (hits, provenance_filter_note) =
        apply_provenance_filter(hits, provenance_classes.as_deref());

    // ── 5. Assemble cited answer ───────────────────────────────────────────────
    // Build the answer via the appropriate path:
    // - synthesized: production-grade LLM attached (is_production_grade = true)
    // - extractive: no model / stub model (keyless installs)
    let answer_result = assemble_answer(runtime, query_text, &hits, as_of.as_deref());

    // ── 6. Stamp confidence ────────────────────────────────────────────────────
    let cited_confidences: Vec<f64> = answer_result
        .citations
        .iter()
        .filter_map(|c| c.confidence)
        .collect();
    let answer_confidence = if cited_confidences.is_empty() {
        Value::Null
    } else {
        #[allow(clippy::cast_precision_loss)]
        let mean = cited_confidences.iter().sum::<f64>() / cited_confidences.len() as f64;
        json!(mean)
    };

    // ── 7. Build response ──────────────────────────────────────────────────────
    let citations_json: Vec<Value> = answer_result
        .citations
        .iter()
        .map(|c| {
            json!({
                "id": c.id,
                "score": c.score,
                "confidence": c.confidence,
                "snippet": c.snippet,
            })
        })
        .collect();

    let mut response = json!({
        "query": query_text,
        "mode": answer_result.mode,
        "answer": answer_result.answer,
        "citations": citations_json,
        "answer_confidence": answer_confidence,
        "as_of": as_of,
        "retrieved_count": hits.len(),
        "leakage_guard": "Temporal predicates enforced by Retriever on every channel. \
                          No fact with as_of > query as_of is in the retrieved set, \
                          citation set, or answer.",
        "citation_validity": "Every cited id exists in the retrieved set (structurally enforced).",
    });

    if let Some(note) = provenance_filter_note {
        response["provenance_filter_note"] = json!(note);
    }
    if let Some(warning) = answer_result.citation_validity_warning {
        response["citation_validity_warning"] = json!(warning);
    }

    Ok(structured(response))
}

// ── Answer assembly ───────────────────────────────────────────────────────────

/// One citation in the answer: a document id that exists in the retrieved set.
#[derive(Debug)]
struct AnswerCitation {
    /// Document id — MUST be in the retrieved set.
    id: String,
    /// Fused RRF score for this hit.
    score: f64,
    /// K-R6 confidence score (None when graph not attached or hit has no edges).
    confidence: Option<f64>,
    /// Leading passage extracted from the hit (extractive path always; synthesized
    /// path also carried for caller transparency).
    snippet: String,
}

/// Result of the answer assembly step.
struct AnswerResult {
    /// One of [`MODE_EXTRACTIVE`] or [`MODE_SYNTHESIZED_STUB`] — always truthful
    /// about whether a production LLM produced the text.
    mode: String,
    /// The answer text (NL synthesis or structured extractive passages).
    answer: String,
    /// Citations — every id in this list is in the retrieved hit set.
    citations: Vec<AnswerCitation>,
    /// Set when a post-generation citation-validity check stripped out-of-set ids
    /// from an LLM-generated answer. `None` on the extractive path or when the LLM
    /// only cited valid ids.
    citation_validity_warning: Option<String>,
}

/// Assemble an answer from the retrieved hit set.
///
/// Chooses between synthesized (production LLM) and extractive (no model / stub)
/// based on `is_production_grade()`.  Both paths carry the same citation contract.
fn assemble_answer(
    runtime: &KnowledgeRuntime,
    query: &str,
    hits: &[tdw_retrieve::RetrievedHit],
    _as_of: Option<&str>,
) -> AnswerResult {
    if hits.is_empty() {
        return AnswerResult {
            mode: MODE_EXTRACTIVE.to_string(),
            answer: "No relevant documents found for this query in the knowledge graph."
                .to_string(),
            citations: Vec::new(),
            citation_validity_warning: None,
        };
    }

    // Build citations from the retrieved set (citation validity: ids come directly
    // from hits — hallucination is structurally impossible at this step).
    let citations: Vec<AnswerCitation> = hits
        .iter()
        .map(|hit| {
            let snippet = extract_snippet(&hit.id, &hit.tags);
            AnswerCitation {
                id: hit.id.clone(),
                score: hit.score,
                confidence: hit.confidence.as_ref().map(|c| c.confidence),
                snippet,
            }
        })
        .collect();

    // Check whether a production-grade LLM is available.
    // KnowledgeRuntime does not hold a language model handle directly; we detect
    // production grade via the structural proxy: adaptivity_resolver + bound_agent_id
    // (same heuristic as `status().language_model_grade`). This is the #345 stub
    // gate referenced in the K-M3 spec.
    let is_production =
        runtime.adaptivity_resolver().is_some() && runtime.bound_agent_id().is_some();

    // Override: TDW_ALLOW_STUB_FEEDBACK=1 lets tests exercise the synthesis path.
    let allow_stub = std::env::var("TDW_ALLOW_STUB_FEEDBACK").ok().as_deref() == Some("1");

    if is_production || allow_stub {
        synthesized_answer(query, hits, citations)
    } else {
        extractive_answer(query, citations)
    }
}

/// Build a structured extractive answer: top passages + citation list.
///
/// Mode stamp: `"extractive (no model configured)"`.
/// Every cited id is in the hit set (citations come directly from hits).
fn extractive_answer(query: &str, citations: Vec<AnswerCitation>) -> AnswerResult {
    let mut answer_parts = vec![format!(
        "Extractive answer for query: \"{query}\"\n\
         (Mode: extractive — no production language model configured. \
         Configure a production LLM to enable NL synthesis.)\n"
    )];

    for (index, citation) in citations.iter().enumerate() {
        answer_parts.push(format!(
            "[{}] {} (score: {:.4}{})\n  {}",
            index + 1,
            citation.id,
            citation.score,
            citation
                .confidence
                .map_or_else(String::new, |c| format!(", confidence: {c:.3}")),
            citation.snippet,
        ));
    }

    AnswerResult {
        mode: MODE_EXTRACTIVE.to_string(),
        answer: answer_parts.join("\n"),
        citations,
        citation_validity_warning: None,
    }
}

/// Build a synthesized NL answer using an inline-citation prompt.
///
/// The LLM prompt would include explicit `[doc-id]` markers so the model can cite
/// retrieved documents. Post-generation, any id in the answer that is NOT in
/// the retrieved set is stripped (citation-validity enforcement) and a warning
/// is attached.
///
/// Mode stamp: [`MODE_SYNTHESIZED_STUB`] — truthfully marks this as a stub, NOT
/// bare `"synthesized"`, so a keyless/stub install can never present fabricated
/// boilerplate as production NL synthesis (K-M3 citation-honesty guarantee).
///
/// # Production-wiring seam (#345)
///
/// `KnowledgeRuntime` does not yet hold a `LanguageModel` handle; the
/// `is_production_grade()` gate is proxied structurally (adaptivity_resolver +
/// bound_agent_id).  Until the composition root wires a real LM this function
/// produces a clearly-labelled stub synthesis so the full synthesized code-path
/// (citation contract, validity check, mode stamp) is exercisable via
/// `TDW_ALLOW_STUB_FEEDBACK=1` without a live API key.
fn synthesized_answer(
    query: &str,
    hits: &[tdw_retrieve::RetrievedHit],
    citations: Vec<AnswerCitation>,
) -> AnswerResult {
    // Build context passages (budgeted per-hit and in aggregate).
    let mut context_chars = 0usize;
    let mut context_parts: Vec<String> = Vec::new();
    for hit in hits {
        if context_chars >= MAX_PROMPT_CONTEXT_CHARS {
            break;
        }
        let snippet = extract_snippet(&hit.id, &hit.tags);
        let passage = format!("[{}] {}", hit.id, truncate_str(&snippet, MAX_PASSAGE_CHARS));
        context_chars += passage.len();
        context_parts.push(passage);
    }
    let _context = context_parts.join("\n\n");

    let valid_ids: std::collections::BTreeSet<&str> = hits.iter().map(|h| h.id.as_str()).collect();

    // Stub synthesis: produce a structured answer referencing only valid ids
    // (for TDW_ALLOW_STUB_FEEDBACK=1 test mode and the #345 production-wiring seam).
    // A real composition root wires a LanguageModel and calls `.complete()` here.
    let stub_answer = build_stub_synthesis(query, hits, &valid_ids);

    // Citation-validity enforcement: scan the generated answer for any [id] that
    // is NOT in valid_ids, collect stripped ids, attach warning if any were removed.
    let (cleaned_answer, stripped_ids) = validate_and_clean_citations(&stub_answer, &valid_ids);

    let citation_validity_warning = if stripped_ids.is_empty() {
        None
    } else {
        Some(format!(
            "citation_validity_filter: {} out-of-set id(s) stripped from the generated answer: {}",
            stripped_ids.len(),
            stripped_ids.join(", ")
        ))
    };

    AnswerResult {
        mode: MODE_SYNTHESIZED_STUB.to_string(),
        answer: cleaned_answer,
        citations,
        citation_validity_warning,
    }
}

/// Build a stub NL synthesis string that references only valid ids.
///
/// Used in the `TDW_ALLOW_STUB_FEEDBACK=1` test path and the #345 seam until a
/// real LanguageModel handle is wired into `KnowledgeRuntime`. The result is
/// clearly synthesized-looking so the synthesized code-path (citation validity
/// check, mode stamp) is fully exercised.
fn build_stub_synthesis(
    query: &str,
    hits: &[tdw_retrieve::RetrievedHit],
    valid_ids: &std::collections::BTreeSet<&str>,
) -> String {
    let citation_list: Vec<String> = hits
        .iter()
        .filter(|h| valid_ids.contains(h.id.as_str()))
        .map(|h| format!("[{}]", h.id))
        .collect();

    let citations_str = if citation_list.is_empty() {
        String::new()
    } else {
        format!(
            " Based on the retrieved knowledge: {}.",
            citation_list.join(", ")
        )
    };

    format!(
        "Based on the available knowledge graph documents, here is a synthesized answer to: \"{query}\".{citations_str} \
         (This answer was assembled from {} retrieved document(s) using the extractive-synthesis hybrid path. \
         Configure a live LanguageModel in the composition root to enable full NL synthesis.)",
        hits.len()
    )
}

/// Scan `answer` for `[id]` tokens and remove any whose `id` is NOT in `valid_ids`.
///
/// Returns `(cleaned_answer, stripped_ids)`.  The structural citation contract
/// means this is defence-in-depth for synthesized mode — on the extractive and
/// stub paths it is always a no-op (no out-of-set ids can appear).
fn validate_and_clean_citations(
    answer: &str,
    valid_ids: &std::collections::BTreeSet<&str>,
) -> (String, Vec<String>) {
    let mut stripped: Vec<String> = Vec::new();
    let mut cleaned = answer.to_string();

    // Scan for [token] patterns; token must match a retrieved id exactly.
    let mut scan = answer;
    while let Some(open) = scan.find('[') {
        let rest = &scan[open + 1..];
        if let Some(close) = rest.find(']') {
            let candidate = &rest[..close];
            // Only treat a bracketed token as a *citation candidate* when it looks
            // like a document id (alphanumerics plus the id punctuation `- _ :`).
            // This prevents corrupting legitimate non-citation prose an LLM may
            // emit, e.g. `[Note: …]`, `[approximate]`, `[1]` — Gemini HIGH.
            let looks_like_id = !candidate.is_empty()
                && candidate
                    .chars()
                    .all(|c| c.is_alphanumeric() || matches!(c, '-' | '_' | ':'));
            if looks_like_id && !valid_ids.contains(candidate) {
                // Strip this citation from the cleaned answer.
                let marker = format!("[{candidate}]");
                cleaned = cleaned.replace(&marker, "");
                if !stripped.contains(&candidate.to_string()) {
                    stripped.push(candidate.to_string());
                }
            }
            scan = &rest[close + 1..];
        } else {
            break;
        }
    }

    (cleaned, stripped)
}

// ── Provenance-class filter (K-X3 trust-dial reuse) ──────────────────────────

/// Apply the provenance-class filter to the retrieved hit set.
///
/// The K-X3 trust-dial filter narrows the hit set to those whose provenance
/// class matches one of the requested classes.  `RetrievedHit` carries
/// `entity_id` and the explanation's channels; it does NOT carry the full edge
/// provenance (that lives in the graph).  We therefore apply the filter at a
/// best-effort level combining the hit's `entity_id` prefix with its channel mix:
///
/// - `ingest` / `manual` / `system` → text-channel hits ([`Channel::Vector`] or
///   [`Channel::Lexical`]) that are NOT `agent:`-prefixed entities.
/// - `agent` → text-channel hits whose `entity_id` starts with `agent:`.
/// - `rule` / `graph` → hits that reached via [`Channel::Graph`], have a graph
///   path, or whose `entity_id` starts with `rule:`.
/// - `tag` → hits that reached via the [`Channel::Tag`] channel.
/// - Unknown class: honest note, no filter applied.
///
/// The `entity_id` prefix is what separates `ingest` from `agent`: both route
/// through the same vector/lexical channels, so channels alone cannot tell them
/// apart.
///
/// When `provenance_classes` is `None` or empty, all hits are returned as-is.
///
/// Returns `(filtered_hits, Option<note>)`.
fn apply_provenance_filter(
    hits: Vec<tdw_retrieve::RetrievedHit>,
    provenance_classes: Option<&[String]>,
) -> (Vec<tdw_retrieve::RetrievedHit>, Option<String>) {
    use tdw_retrieve::Channel;

    let Some(classes) = provenance_classes else {
        return (hits, None);
    };
    if classes.is_empty() {
        return (hits, None);
    }

    // Normalise requested classes to lowercase.
    let classes_lower: Vec<String> = classes.iter().map(|c| c.to_ascii_lowercase()).collect();

    let want_ingest = classes_lower
        .iter()
        .any(|c| matches!(c.as_str(), "ingest" | "manual" | "system"));
    let want_rule = classes_lower
        .iter()
        .any(|c| matches!(c.as_str(), "rule" | "graph"));
    let want_agent = classes_lower.iter().any(|c| c.as_str() == "agent");
    let want_tag = classes_lower.iter().any(|c| c.as_str() == "tag");

    // Unknown classes (not recognized by any of the above).
    let known: &[&str] = &[
        "ingest", "manual", "system", "rule", "graph", "agent", "tag",
    ];
    let unknown: Vec<&str> = classes_lower
        .iter()
        .map(String::as_str)
        .filter(|c| !known.contains(c))
        .collect();
    let note = if unknown.is_empty() {
        None
    } else {
        Some(format!(
            "Provenance classes not recognized (treated as no-filter): {}. \
             Known classes: {}.",
            unknown.join(", "),
            known.join(", ")
        ))
    };

    let filtered = hits
        .into_iter()
        .filter(|hit| {
            let channels: Vec<Channel> =
                hit.explanation.channels.iter().map(|c| c.channel).collect();
            let has_graph_path = hit.explanation.graph_path.is_some();

            // Apply the documented entity_id-prefix heuristic so `ingest` and
            // `agent` are actually distinguishable (Gemini MEDIUM): agent-authored
            // facts carry an `agent:` entity prefix, rule-derived facts a `rule:`
            // prefix. Channels alone cannot separate ingest from agent because both
            // route through the vector/lexical stores.
            let is_agent_entity = hit.entity_id.starts_with("agent:");
            let is_rule_entity = hit.entity_id.starts_with("rule:");
            let text_channel = channels
                .iter()
                .any(|c| matches!(c, Channel::Vector | Channel::Lexical));

            let passes_ingest = want_ingest && text_channel && !is_agent_entity;
            let passes_rule = want_rule
                && (channels.contains(&Channel::Graph) || has_graph_path || is_rule_entity);
            let passes_agent = want_agent && text_channel && is_agent_entity;
            let passes_tag = want_tag && channels.contains(&Channel::Tag);

            // If none of the requested classes matched any known category, include all.
            if !want_ingest && !want_rule && !want_agent && !want_tag {
                return true;
            }

            passes_ingest || passes_rule || passes_agent || passes_tag
        })
        .collect();

    (filtered, note)
}

// ── Snippet extraction ────────────────────────────────────────────────────────

/// Extract a brief passage from a hit.
///
/// `RetrievedHit` carries `id`, `entity_id`, `score`, `tags`, and
/// `explanation` but NOT the raw document body (that lives in the vector /
/// lexical stores, not in the graph hit).  We compose a meaningful snippet
/// from the available structured metadata: the hit id (which encodes the
/// document identifier) and the matched tags.
///
/// A full composition root can inject body text by querying the lexical engine
/// before assembly; for now an honest "metadata-only" snippet is returned so
/// the extractive path is functional for keyless installs without requiring an
/// additional engine round-trip per hit.
fn extract_snippet(id: &str, tags: &[String]) -> String {
    let tag_str = if tags.is_empty() {
        String::new()
    } else {
        format!(" [tags: {}]", tags.join(", "))
    };
    format!("Document: {id}{tag_str}")
}

/// Truncate `s` to at most `max_chars` characters, appending `…` when truncated.
///
/// Returns a [`Cow`](std::borrow::Cow) so the (common) no-truncation case stays
/// borrow-only while the truncated case can actually append the ellipsis the
/// docstring promises — Gemini MEDIUM.
fn truncate_str(s: &str, max_chars: usize) -> std::borrow::Cow<'_, str> {
    if s.chars().count() <= max_chars {
        std::borrow::Cow::Borrowed(s)
    } else {
        // Find the byte offset of the max_chars-th character boundary.
        let byte_offset = s
            .char_indices()
            .nth(max_chars)
            .map_or(s.len(), |(offset, _)| offset);
        std::borrow::Cow::Owned(format!("{}…", &s[..byte_offset]))
    }
}

// ── Argument helpers (mirrors knowledge_tools.rs) ─────────────────────────────

fn require_str<'a>(arguments: &'a Map<String, Value>, name: &str) -> Result<&'a str, ToolFailure> {
    optional_str(arguments, name)
        .ok_or_else(|| execution(format!("missing required argument: {name}")))
}

fn optional_str<'a>(arguments: &'a Map<String, Value>, name: &str) -> Option<&'a str> {
    arguments.get(name).and_then(Value::as_str)
}

fn optional_usize(
    arguments: &Map<String, Value>,
    name: &str,
) -> Result<Option<usize>, ToolFailure> {
    match arguments.get(name) {
        None | Some(Value::Null) => Ok(None),
        Some(value) => value
            .as_u64()
            .and_then(|n| usize::try_from(n).ok())
            .map(Some)
            .ok_or_else(|| execution(format!("{name} must be a non-negative integer"))),
    }
}

fn optional_u8(arguments: &Map<String, Value>, name: &str) -> Result<Option<u8>, ToolFailure> {
    match arguments.get(name) {
        None | Some(Value::Null) => Ok(None),
        Some(value) => value
            .as_u64()
            .and_then(|n| u8::try_from(n).ok())
            .map(Some)
            .ok_or_else(|| execution(format!("{name} must be an integer in 0..=255"))),
    }
}

fn optional_string_array(
    arguments: &Map<String, Value>,
    name: &str,
) -> Result<Option<Vec<String>>, ToolFailure> {
    match arguments.get(name) {
        None | Some(Value::Null) => Ok(None),
        Some(Value::Array(items)) => items
            .iter()
            .map(|item| {
                item.as_str()
                    .map(ToString::to_string)
                    .ok_or_else(|| execution(format!("{name} must be an array of strings")))
            })
            .collect::<Result<Vec<_>, _>>()
            .map(Some),
        Some(_) => Err(execution(format!("{name} must be an array of strings"))),
    }
}

const fn execution(message: String) -> ToolFailure {
    ToolFailure::Execution(message)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    fn ids<'a>(slice: &'a [&'a str]) -> BTreeSet<&'a str> {
        slice.iter().copied().collect()
    }

    #[test]
    fn clean_citations_strips_out_of_set_ids() {
        let valid = ids(&["doc-aapl"]);
        let (cleaned, stripped) =
            validate_and_clean_citations("see [doc-aapl] and [doc-ghost]", &valid);
        assert!(cleaned.contains("[doc-aapl]"), "valid id kept: {cleaned}");
        assert!(!cleaned.contains("[doc-ghost]"), "ghost stripped: {cleaned}");
        assert_eq!(stripped, vec!["doc-ghost".to_string()]);
    }

    #[test]
    fn clean_citations_preserves_non_citation_brackets() {
        // Gemini HIGH: legitimate bracketed prose with spaces/punctuation must
        // survive — only document-id-shaped tokens are citation candidates.
        let valid = ids(&["doc-aapl"]);
        let answer = "Answer [Note: see filing] with [doc-aapl] context.";
        let (cleaned, stripped) = validate_and_clean_citations(answer, &valid);
        assert!(
            cleaned.contains("[Note: see filing]"),
            "non-citation prose must be preserved: {cleaned}"
        );
        assert!(cleaned.contains("[doc-aapl]"));
        assert!(
            stripped.is_empty(),
            "no id-shaped out-of-set token to strip: {stripped:?}"
        );
    }

    #[test]
    fn truncate_str_appends_ellipsis_only_when_truncated() {
        // Gemini MEDIUM: ellipsis must actually be appended on truncation.
        assert_eq!(truncate_str("short", 32), "short");
        let truncated = truncate_str("abcdef", 3);
        assert_eq!(truncated, "abc…");
        assert!(truncated.ends_with('…'));
    }

    #[test]
    fn stub_synthesis_mode_stamp_is_never_bare_synthesized() {
        // K-M3 citation honesty: the stub stamp must declare itself a stub so it
        // is never mistaken for production NL synthesis.
        assert_ne!(MODE_SYNTHESIZED_STUB, "synthesized");
        assert!(MODE_SYNTHESIZED_STUB.contains("stub"));
    }
}
