[package]
name = "tdw-hooks"
version = "0.1.0"
edition = "2024"
publish = false
license = "UNLICENSED"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tdw-event = { path = "../tdw-event" }
tdw-protocol = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
