[package]
name = "tdw-provider-yahoo"
version = "0.1.0"
edition = "2024"
publish = false
license = "UNLICENSED"

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tdw-core = { workspace = true }
tdw-domain = { workspace = true }
tdw-provider-fileset = { path = "../tdw-provider-fileset" }

[lints]
workspace = true
