[package]
name = "tdw-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
bytes = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }

[build-dependencies]
prost-build = { git = "https://github.com/plabayo/rust-protobuf", package = "prost-build" }

[lints]
workspace = true
