[package]
name = "tdw-taxonomy"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
schemars = { workspace = true }
serde = { workspace = true }
validator = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
