[package]
name = "tdw-domain"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
validator = { workspace = true }

[lints]
workspace = true

[[example]]
name = "tdw-domain-basic"
path = "examples/basic.rs"
