[package]
name = "tdw-tag-rules"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
serde = { workspace = true }
tdw-tags = { path = "../tdw-tags" }
thiserror = { workspace = true }

[lints]
workspace = true

[[example]]
name = "tdw-tag-rules-basic"
path = "examples/basic.rs"
