# @generated by `cargo run -p xtask -- pysdk-sync` from the endpoint catalog.
# Do not edit by hand; regenerate and commit instead. Drift is gated by `pysdk-check`.

"""FinX Platform Python SDK — a thin, generated HTTP client over the daemon's REST API.

Install the package and call catalog routes with OpenBB-style ergonomics::

    from finx_platform import FinX

    finx = FinX()  # base_url from FINX_BASE_URL or the loopback default
    obj = finx.equity.price.historical(symbol="AAPL", provider="yahoo")
    df = obj.to_dataframe()

The client targets a locally running daemon with the REST surface enabled
(``TDW_DAEMON_REST_BIND``). Only ``Fetch`` routes are REST-served; compute
routes (``technical/*``) raise ``NotImplementedError``.
"""

from __future__ import annotations

from ._client import Client, FinXObject
from .commodity import CommodityNamespace
from .crypto import CryptoNamespace
from .currency import CurrencyNamespace
from .derivatives import DerivativesNamespace
from .econometrics import EconometricsNamespace
from .economy import EconomyNamespace
from .equity import EquityNamespace
from .etf import EtfNamespace
from .fixedincome import FixedincomeNamespace
from .index import IndexNamespace
from .quantitative import QuantitativeNamespace
from .regulators import RegulatorsNamespace
from .technical import TechnicalNamespace

__all__ = [
    "FinX",
    "FinXObject",
    "Client",
]

__version__ = "0.1.0"


class FinX:
    """The SDK entry point: a REST client plus one accessor per router namespace.

    Parameters mirror :class:`finx_platform._client.Client`; ``base_url`` falls
    back to the ``FINX_BASE_URL`` environment variable and then the loopback
    default.
    """

    def __init__(
        self,
        base_url: str | None = None,
        *,
        timeout: float = 30.0,
        client: Client | None = None,
    ) -> None:
        self._client = client if client is not None else Client(base_url, timeout=timeout)
        self.commodity = CommodityNamespace(self._client)
        self.crypto = CryptoNamespace(self._client)
        self.currency = CurrencyNamespace(self._client)
        self.derivatives = DerivativesNamespace(self._client)
        self.econometrics = EconometricsNamespace(self._client)
        self.economy = EconomyNamespace(self._client)
        self.equity = EquityNamespace(self._client)
        self.etf = EtfNamespace(self._client)
        self.fixedincome = FixedincomeNamespace(self._client)
        self.index = IndexNamespace(self._client)
        self.quantitative = QuantitativeNamespace(self._client)
        self.regulators = RegulatorsNamespace(self._client)
        self.technical = TechnicalNamespace(self._client)

