# @generated by `cargo run -p xtask -- pysdk-sync` from the endpoint catalog.
# Do not edit by hand; regenerate and commit instead. Drift is gated by `pysdk-check`.

"""Generated ``crypto`` router namespace for the FinX Platform SDK."""

from __future__ import annotations

from ._client import Client, FinXObject


class CryptoPriceNamespace:
    """Accessor for the ``crypto/price`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def historical(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """Historical OHLCV bars for a crypto trading pair.

        Route: ``crypto/price/historical``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("crypto/price/historical", params)

class CryptoNamespace:
    """Accessor for the ``crypto`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client
        self.price = CryptoPriceNamespace(client)

    # (no terminal routes at this namespace level)
