# @generated by `cargo run -p xtask -- pysdk-sync` from the endpoint catalog.
# Do not edit by hand; regenerate and commit instead. Drift is gated by `pysdk-check`.

"""Generated ``econometrics`` router namespace for the FinX Platform SDK."""

from __future__ import annotations

from ._client import Client, FinXObject


class EconometricsNamespace:
    """Accessor for the ``econometrics`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def cointegration(
        self,
        *,
        x: str | None = None,
        y: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Engle-Granger step one plus a residual stationarity score.

        Route: ``econometrics/cointegration``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            x: The second (regressor) level series `x`.
            y: The first (dependent) level series `y`.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'econometrics/cointegration' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def correlation_matrix(
        self,
        *,
        columns: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Pearson correlation matrix of a set of equal-length columns.

        Route: ``econometrics/correlation_matrix``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            columns: The columns to correlate / score, each the same length.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'econometrics/correlation_matrix' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def granger_causality(
        self,
        *,
        lag: int | None = None,
        x: str | None = None,
        y: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Granger-causality F-test of x-lags improving the prediction of y.

        Route: ``econometrics/granger_causality``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            lag: Number of lags of each series to include (default `1`).
            x: The candidate causal series `x` whose lags may improve `y`'s prediction.
            y: The dependent series `y` whose prediction is tested.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'econometrics/granger_causality' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def ols(
        self,
        *,
        intercept: bool | None = None,
        x: str | None = None,
        y: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Ordinary least squares: coefficients, std errors, t-stats, R2, F, DW.

        Route: ``econometrics/ols``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            intercept: Whether to prepend an intercept column of ones (default `true`).
            x: Design columns: `x[j]` is the `j`-th regressor, each the same length as `y`. The intercept is added separately (see `intercept`), so do not include a column of ones.
            y: Response vector (one value per observation).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'econometrics/ols' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def vif(
        self,
        *,
        columns: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Variance inflation factors via auxiliary-regression R-squared.

        Route: ``econometrics/vif``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            columns: The columns to correlate / score, each the same length.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'econometrics/vif' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )
