# @generated by `cargo run -p xtask -- pysdk-sync` from the endpoint catalog.
# Do not edit by hand; regenerate and commit instead. Drift is gated by `pysdk-check`.

"""Generated ``equity`` router namespace for the FinX Platform SDK."""

from __future__ import annotations

from ._client import Client, FinXObject


class EquityCalendarNamespace:
    """Accessor for the ``equity/calendar`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def dividends(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Upcoming dividend calendar (ex-date, amount, pay date), NASDAQ-backed.

        Route: ``equity/calendar/dividends``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("equity/calendar/dividends", params)

    def earnings(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Upcoming earnings calendar (date, EPS estimate), NASDAQ-backed.

        Route: ``equity/calendar/earnings``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("equity/calendar/earnings", params)

    def ipo(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Upcoming IPO calendar (price, shares, exchange), NASDAQ-backed.

        Route: ``equity/calendar/ipo``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("equity/calendar/ipo", params)

class EquityEstimatesNamespace:
    """Accessor for the ``equity/estimates`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def consensus(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Analyst consensus and price targets for a symbol, Yahoo-backed.

        Route: ``equity/estimates/consensus``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("equity/estimates/consensus", params)

class EquityFundamentalNamespace:
    """Accessor for the ``equity/fundamental`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def balance(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Balance sheet (assets, liabilities, equity) per period, FMP-backed.

        Route: ``equity/fundamental/balance``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("equity/fundamental/balance", params)

    def cash(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Cash-flow statement (operating/investing/financing) per period, FMP-backed.

        Route: ``equity/fundamental/cash``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("equity/fundamental/cash", params)

    def dividends(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Historical cash dividends for an equity symbol, Yahoo-backed.

        Route: ``equity/fundamental/dividends``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("equity/fundamental/dividends", params)

    def income(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Income statement (revenue, margins, net income) per period, FMP-backed.

        Route: ``equity/fundamental/income``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("equity/fundamental/income", params)

    def metrics(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Key metrics (per-share and valuation), FMP-backed.

        Route: ``equity/fundamental/metrics``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("equity/fundamental/metrics", params)

    def ratios(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Financial ratios (liquidity, profitability, leverage), FMP-backed.

        Route: ``equity/fundamental/ratios``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("equity/fundamental/ratios", params)

class EquityOwnershipNamespace:
    """Accessor for the ``equity/ownership`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def form_13f(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """SEC Form 13F-HR institutional-holdings filing index by CIK (keyless).

        Route: ``equity/ownership/form_13f``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("equity/ownership/form_13f", params)

    def share_statistics(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Share statistics (float, shares outstanding, ownership), Yahoo-backed.

        Route: ``equity/ownership/share_statistics``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("equity/ownership/share_statistics", params)

class EquityPriceNamespace:
    """Accessor for the ``equity/price`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def historical(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """Historical end-of-day OHLCV bars for an equity symbol.

        Route: ``equity/price/historical``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("equity/price/historical", params)

    def performance(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Period total returns (one-day through one-year) for a symbol, Yahoo-backed.

        Route: ``equity/price/performance``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("equity/price/performance", params)

    def quote(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Current last-price quote snapshot for an equity symbol, Yahoo-backed.

        Route: ``equity/price/quote``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("equity/price/quote", params)

class EquityShortsNamespace:
    """Accessor for the ``equity/shorts`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def fails_to_deliver(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """SEC fails-to-deliver records for an equity symbol (keyless).

        Route: ``equity/shorts/fails_to_deliver``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("equity/shorts/fails_to_deliver", params)

class EquityNamespace:
    """Accessor for the ``equity`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client
        self.calendar = EquityCalendarNamespace(client)
        self.estimates = EquityEstimatesNamespace(client)
        self.fundamental = EquityFundamentalNamespace(client)
        self.ownership = EquityOwnershipNamespace(client)
        self.price = EquityPriceNamespace(client)
        self.shorts = EquityShortsNamespace(client)

    def profile(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Company profile (name, exchange, currency, market cap); Yahoo (keyless) then FMP candidate.

        Route: ``equity/profile``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("equity/profile", params)
