# @generated by `cargo run -p xtask -- pysdk-sync` from the endpoint catalog.
# Do not edit by hand; regenerate and commit instead. Drift is gated by `pysdk-check`.

"""Generated ``fixedincome`` router namespace for the FinX Platform SDK."""

from __future__ import annotations

from ._client import Client, FinXObject


class FixedincomeBondIndicesNamespace:
    """Accessor for the ``fixedincome/bond_indices`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def us_corporate_hy(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """ICE BofA US High Yield index effective yield, FRED-backed rate observation.

        Route: ``fixedincome/bond_indices/us_corporate_hy``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/bond_indices/us_corporate_hy", params)

    def us_corporate_ig(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """ICE BofA US Corporate (investment-grade) index option-adjusted spread, FRED-backed.

        Route: ``fixedincome/bond_indices/us_corporate_ig``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/bond_indices/us_corporate_ig", params)

    def us_high_yield_oas(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """ICE BofA US High Yield index option-adjusted spread, FRED-backed rate observation.

        Route: ``fixedincome/bond_indices/us_high_yield_oas``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/bond_indices/us_high_yield_oas", params)

class FixedincomeCorporateCommercialPaperNamespace:
    """Accessor for the ``fixedincome/corporate/commercial_paper`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def t_90d(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """90-Day AA nonfinancial commercial paper rate, FRED-backed rate observation.

        Route: ``fixedincome/corporate/commercial_paper/90d``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/corporate/commercial_paper/90d", params)

class FixedincomeCorporateHqmNamespace:
    """Accessor for the ``fixedincome/corporate/hqm`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def t_2y(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """2-Year HQM corporate bond yield-curve spot rate, FRED-backed rate observation.

        Route: ``fixedincome/corporate/hqm/2y``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/corporate/hqm/2y", params)

    def t_30y(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """30-Year HQM corporate bond yield-curve spot rate, FRED-backed rate observation.

        Route: ``fixedincome/corporate/hqm/30y``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/corporate/hqm/30y", params)

    def t_5y(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """5-Year HQM corporate bond yield-curve spot rate, FRED-backed rate observation.

        Route: ``fixedincome/corporate/hqm/5y``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/corporate/hqm/5y", params)

class FixedincomeCorporateMoodyNamespace:
    """Accessor for the ``fixedincome/corporate/moody`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def aaa(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """Moody's Seasoned Aaa corporate bond yield, FRED-backed rate observation.

        Route: ``fixedincome/corporate/moody/aaa``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/corporate/moody/aaa", params)

    def baa(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """Moody's Seasoned Baa corporate bond yield, FRED-backed rate observation.

        Route: ``fixedincome/corporate/moody/baa``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/corporate/moody/baa", params)

class FixedincomeCorporateSpotRatesNamespace:
    """Accessor for the ``fixedincome/corporate/spot_rates`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def t_10y(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """10-Year HQM corporate bond spot rate, FRED-backed rate observation.

        Route: ``fixedincome/corporate/spot_rates/10y``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/corporate/spot_rates/10y", params)

class FixedincomeCorporateNamespace:
    """Accessor for the ``fixedincome/corporate`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client
        self.commercial_paper = FixedincomeCorporateCommercialPaperNamespace(client)
        self.hqm = FixedincomeCorporateHqmNamespace(client)
        self.moody = FixedincomeCorporateMoodyNamespace(client)
        self.spot_rates = FixedincomeCorporateSpotRatesNamespace(client)

    def ice_bofa(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """ICE BofA US Corporate Index effective yield, FRED-backed rate observation.

        Route: ``fixedincome/corporate/ice_bofa``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/corporate/ice_bofa", params)

class FixedincomeGovernmentSvenssonYieldCurveNamespace:
    """Accessor for the ``fixedincome/government/svensson_yield_curve`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def t_10y(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """10-Year Svensson (GSW) fitted zero-coupon yield, FRED-backed rate observation.

        Route: ``fixedincome/government/svensson_yield_curve/10y``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/government/svensson_yield_curve/10y", params)

    def t_2y(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """2-Year Svensson (GSW) fitted zero-coupon yield, FRED-backed rate observation.

        Route: ``fixedincome/government/svensson_yield_curve/2y``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/government/svensson_yield_curve/2y", params)

    def t_5y(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """5-Year Svensson (GSW) fitted zero-coupon yield, FRED-backed rate observation.

        Route: ``fixedincome/government/svensson_yield_curve/5y``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/government/svensson_yield_curve/5y", params)

class FixedincomeGovernmentTipsYieldsNamespace:
    """Accessor for the ``fixedincome/government/tips_yields`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def t_10y(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """10-Year TIPS constant-maturity yield, FRED-backed rate observation.

        Route: ``fixedincome/government/tips_yields/10y``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/government/tips_yields/10y", params)

class FixedincomeGovernmentTreasuryRatesNamespace:
    """Accessor for the ``fixedincome/government/treasury_rates`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def t_10y(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """10-Year Treasury constant-maturity yield, FRED-backed rate observation.

        Route: ``fixedincome/government/treasury_rates/10y``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/government/treasury_rates/10y", params)

    def t_2y(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """2-Year Treasury constant-maturity yield, FRED-backed rate observation.

        Route: ``fixedincome/government/treasury_rates/2y``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/government/treasury_rates/2y", params)

    def t_30y(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """30-Year Treasury constant-maturity yield, FRED-backed rate observation.

        Route: ``fixedincome/government/treasury_rates/30y``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/government/treasury_rates/30y", params)

    def t_3m(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """3-Month Treasury constant-maturity yield, FRED-backed rate observation.

        Route: ``fixedincome/government/treasury_rates/3m``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/government/treasury_rates/3m", params)

class FixedincomeGovernmentNamespace:
    """Accessor for the ``fixedincome/government`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client
        self.svensson_yield_curve = FixedincomeGovernmentSvenssonYieldCurveNamespace(client)
        self.tips_yields = FixedincomeGovernmentTipsYieldsNamespace(client)
        self.treasury_rates = FixedincomeGovernmentTreasuryRatesNamespace(client)

    def dealer_stats(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """Primary dealer net positioning statistics (Federal Reserve, keyless).

        Route: ``fixedincome/government/dealer_stats``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/government/dealer_stats", params)

    def treasury_auctions(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """US Treasury security auction results (US Treasury FiscalData, keyless).

        Route: ``fixedincome/government/treasury_auctions``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("fixedincome/government/treasury_auctions", params)

    def treasury_prices(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """US Treasury security reference prices (US Treasury FiscalData, keyless).

        Route: ``fixedincome/government/treasury_prices``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/government/treasury_prices", params)

    def yield_curve(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """US Treasury yield curve (3m/2y/10y/30y), aggregated from FRED constant-maturity series.

        Route: ``fixedincome/government/yield_curve``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/government/yield_curve", params)

class FixedincomeMortgageIndicesNamespace:
    """Accessor for the ``fixedincome/mortgage_indices`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def t_15y_fixed(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """15-Year fixed-rate mortgage average, FRED-backed rate observation.

        Route: ``fixedincome/mortgage_indices/15y_fixed``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/mortgage_indices/15y_fixed", params)

    def t_30y_fixed(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """30-Year fixed-rate mortgage average, FRED-backed rate observation.

        Route: ``fixedincome/mortgage_indices/30y_fixed``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/mortgage_indices/30y_fixed", params)

class FixedincomeRateEffrForecastNamespace:
    """Accessor for the ``fixedincome/rate/effr_forecast`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def long_run(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """FOMC longer-run median fed-funds-rate projection, FRED-backed rate observation.

        Route: ``fixedincome/rate/effr_forecast/long_run``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/rate/effr_forecast/long_run", params)

class FixedincomeRateNamespace:
    """Accessor for the ``fixedincome/rate`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client
        self.effr_forecast = FixedincomeRateEffrForecastNamespace(client)

    def ameribor(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """Overnight Unsecured AMERIBOR benchmark rate, FRED-backed rate observation.

        Route: ``fixedincome/rate/ameribor``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/rate/ameribor", params)

    def dpcredit(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """Discount window primary credit rate, FRED-backed rate observation.

        Route: ``fixedincome/rate/dpcredit``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/rate/dpcredit", params)

    def ecb(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """ECB deposit facility rate, FRED-backed rate observation.

        Route: ``fixedincome/rate/ecb``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/rate/ecb", params)

    def effr(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """Effective Federal Funds Rate, FRED-backed rate observation.

        Route: ``fixedincome/rate/effr``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/rate/effr", params)

    def effr_forecast_route(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """FOMC median fed-funds-rate projection, FRED-backed rate observation.

        Route: ``fixedincome/rate/effr_forecast``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/rate/effr_forecast", params)

    def estr(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """Euro Short-Term Rate (€STR), FRED-backed rate observation.

        Route: ``fixedincome/rate/estr``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/rate/estr", params)

    def iorb(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """Interest Rate on Reserve Balances, FRED-backed rate observation.

        Route: ``fixedincome/rate/iorb``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/rate/iorb", params)

    def overnight_bank_funding(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """Overnight Bank Funding Rate, FRED-backed rate observation.

        Route: ``fixedincome/rate/overnight_bank_funding``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/rate/overnight_bank_funding", params)

    def sofr(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """Secured Overnight Financing Rate, FRED-backed rate observation.

        Route: ``fixedincome/rate/sofr``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/rate/sofr", params)

    def sonia(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """Sterling Overnight Index Average (SONIA), FRED-backed rate observation.

        Route: ``fixedincome/rate/sonia``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/rate/sonia", params)

class FixedincomeSpreadsTcmNamespace:
    """Accessor for the ``fixedincome/spreads/tcm`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def t_10y2y(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """10-Year minus 2-Year Treasury constant-maturity spread, FRED-backed.

        Route: ``fixedincome/spreads/tcm/10y2y``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/spreads/tcm/10y2y", params)

    def t_10y3m(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """10-Year minus 3-Month Treasury constant-maturity spread, FRED-backed.

        Route: ``fixedincome/spreads/tcm/10y3m``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/spreads/tcm/10y3m", params)

class FixedincomeSpreadsTcmEffrNamespace:
    """Accessor for the ``fixedincome/spreads/tcm_effr`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def t_10y(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """10-Year Treasury constant-maturity minus Federal Funds Rate spread, FRED-backed.

        Route: ``fixedincome/spreads/tcm_effr/10y``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/spreads/tcm_effr/10y", params)

    def t_1y(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """1-Year Treasury constant-maturity minus Federal Funds Rate spread, FRED-backed.

        Route: ``fixedincome/spreads/tcm_effr/1y``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/spreads/tcm_effr/1y", params)

class FixedincomeSpreadsTreasuryEffrNamespace:
    """Accessor for the ``fixedincome/spreads/treasury_effr`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def t_3m(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        chart: bool = False,
        **kwargs: object,
    ) -> FinXObject:
        """3-Month Treasury minus Federal Funds Rate spread, FRED-backed.

        Route: ``fixedincome/spreads/treasury_effr/3m``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            chart: When ``True``, request a server-rendered chart in ``extra``.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        if chart:
            params["chart"] = "true"
        return self._client.fetch("fixedincome/spreads/treasury_effr/3m", params)

class FixedincomeSpreadsNamespace:
    """Accessor for the ``fixedincome/spreads`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client
        self.tcm = FixedincomeSpreadsTcmNamespace(client)
        self.tcm_effr = FixedincomeSpreadsTcmEffrNamespace(client)
        self.treasury_effr = FixedincomeSpreadsTreasuryEffrNamespace(client)

    # (no terminal routes at this namespace level)

class FixedincomeNamespace:
    """Accessor for the ``fixedincome`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client
        self.bond_indices = FixedincomeBondIndicesNamespace(client)
        self.corporate = FixedincomeCorporateNamespace(client)
        self.government = FixedincomeGovernmentNamespace(client)
        self.mortgage_indices = FixedincomeMortgageIndicesNamespace(client)
        self.rate = FixedincomeRateNamespace(client)
        self.spreads = FixedincomeSpreadsNamespace(client)

    # (no terminal routes at this namespace level)
