# @generated by `cargo run -p xtask -- pysdk-sync` from the endpoint catalog.
# Do not edit by hand; regenerate and commit instead. Drift is gated by `pysdk-check`.

"""Generated ``forecast`` router namespace for the FinX Platform SDK."""

from __future__ import annotations

from ._client import Client, FinXObject


class ForecastNamespace:
    """Accessor for the ``forecast`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def anomaly(
        self,
        *,
        lower_quantile: float | None = None,
        upper_quantile: float | None = None,
        y: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Quantile-band anomaly detection: flag points outside the empirical quantile band.

        Route: ``forecast/anomaly``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            lower_quantile: Lower quantile in `[0, 1]`; values below this empirical quantile are flagged. Defaults to `0.05`.
            upper_quantile: Upper quantile in `[0, 1]`; values above this empirical quantile are flagged. Defaults to `0.95`.
            y: Observations to scan for anomalies, in time order.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'forecast/anomaly' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def backtest(
        self,
        *,
        horizon: int | None = None,
        initial: int | None = None,
        model: str | None = None,
        period: int | None = None,
        y: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Expanding-window backtest of a forecast model scored with RMSE/MAE/MAPE/SMAPE.

        Route: ``forecast/backtest``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            horizon: Forecast horizon evaluated at each origin (`>= 1`); the metric compares the `horizon`-step-ahead forecast against the realized values. Defaults to `1`.
            initial: Number of initial observations in the first training window (`>= 1`). The window then expands by `step` at each fold. Defaults to half the series when `0`.
            model: The forecast model re-fit at each expanding-window origin.
            period: Seasonal period for the seasonal-naive / Holt-Winters models (`>= 2` to enable seasonality). Defaults to `0`.
            y: Historical observations in time order (oldest first).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'forecast/backtest' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def ets(
        self,
        *,
        horizon: int | None = None,
        period: int | None = None,
        y: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """ETS additive model selection over the level/trend/seasonal variants by one-step SSE.

        Route: ``forecast/ets``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            horizon: Number of future steps to forecast (`>= 1`).
            period: Candidate additive seasonal period (`>= 2` to include the seasonal variant). Defaults to `0` (only the non-seasonal variants are considered).
            y: Historical observations in time order (oldest first).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'forecast/ets' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def expo(
        self,
        *,
        alpha: float | None = None,
        beta: float | None = None,
        gamma: float | None = None,
        horizon: int | None = None,
        period: int | None = None,
        y: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Holt-Winters exponential smoothing (level + trend + optional additive seasonal).

        Route: ``forecast/expo``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            alpha: Level smoothing coefficient `alpha` in `[0, 1]`.
            beta: Trend smoothing coefficient `beta` in `[0, 1]`. When `0` the forecast has no evolving trend (simple/level smoothing toward a fixed slope).
            gamma: Seasonal smoothing coefficient `gamma` in `[0, 1]`; used only when `period >= 2`.
            horizon: Number of future steps to forecast (`>= 1`).
            period: Additive seasonal period (`>= 2` to enable the seasonal component). When `0` or `1` the model is non-seasonal (Holt's linear trend). Defaults to `0` (non-seasonal).
            y: Historical observations in time order (oldest first).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'forecast/expo' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def linregr(
        self,
        *,
        covariates: str | None = None,
        horizon: int | None = None,
        lags: int | None = None,
        y: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Linear-regression forecast with autoregressive lag features and optional covariates.

        Route: ``forecast/linregr``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            covariates: Optional exogenous covariate columns. Each column must have length `y.len() + horizon`: the first `y.len()` values align to the history and the trailing `horizon` values supply the future covariate path used to extrapolate. Omit (empty) for a pure autoregressive forecast.
            horizon: Number of future steps to forecast (`>= 1`).
            lags: Number of autoregressive lag features `y_{t-1} .. y_{t-lags}` (`>= 1`).
            y: Historical observations in time order (oldest first).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'forecast/linregr' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def metrics(
        self,
        *,
        actual: str | None = None,
        forecast: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Precision metrics RMSE/MAE/MAPE/SMAPE over an aligned actual/forecast pair.

        Route: ``forecast/metrics``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            actual: The realized values.
            forecast: The forecast values, aligned 1:1 with `actual`.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'forecast/metrics' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def mstl(
        self,
        *,
        period: int | None = None,
        y: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Additive moving-average seasonal-trend decomposition (trend + seasonal + residual).

        Route: ``forecast/mstl``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            period: Seasonal period (`>= 2`).
            y: Historical observations in time order (oldest first).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'forecast/mstl' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def rwd(
        self,
        *,
        horizon: int | None = None,
        period: int | None = None,
        y: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Random-walk-with-drift baseline: extrapolate the mean first difference.

        Route: ``forecast/rwd``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            horizon: Number of future steps to forecast (`>= 1`).
            period: Seasonal period (`>= 2`); used only by the seasonal-naive baseline (the last full season is repeated). Ignored by random-walk-with-drift. Defaults to `1`, which the seasonal-naive route rejects as having no seasonal structure.
            y: Historical observations in time order (oldest first).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'forecast/rwd' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def seasonalnaive(
        self,
        *,
        horizon: int | None = None,
        period: int | None = None,
        y: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Seasonal-naive baseline: tile the last full season forward over the horizon.

        Route: ``forecast/seasonalnaive``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            horizon: Number of future steps to forecast (`>= 1`).
            period: Seasonal period (`>= 2`); used only by the seasonal-naive baseline (the last full season is repeated). Ignored by random-walk-with-drift. Defaults to `1`, which the seasonal-naive route rejects as having no seasonal structure.
            y: Historical observations in time order (oldest first).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'forecast/seasonalnaive' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def theta(
        self,
        *,
        horizon: int | None = None,
        y: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """The Theta method (theta = 2): a strong classical baseline carrying a regression drift.

        Route: ``forecast/theta``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            horizon: Number of future steps to forecast (`>= 1`).
            y: Historical observations in time order (oldest first).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'forecast/theta' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )
