# @generated by `cargo run -p xtask -- pysdk-sync` from the endpoint catalog.
# Do not edit by hand; regenerate and commit instead. Drift is gated by `pysdk-check`.

"""Generated ``portfolio`` router namespace for the FinX Platform SDK."""

from __future__ import annotations

from ._client import Client, FinXObject


class PortfolioNamespace:
    """Accessor for the ``portfolio`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def allocation(
        self,
        *,
        values: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Normalize position values to portfolio weights summing to one.

        Route: ``portfolio/allocation``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            values: Per-position market values (any currency unit); they are divided by their total to yield weights summing to `1`.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'portfolio/allocation' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def contribution(
        self,
        *,
        returns: str | None = None,
        weights: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Per-asset return contribution: weight times return for each asset.

        Route: ``portfolio/contribution``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            returns: Per-asset returns, aligned one-to-one with `weights`.
            weights: Per-asset portfolio weights (typically summing to `1`, but not required).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'portfolio/contribution' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def cumulative_returns(
        self,
        *,
        returns: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Running compounded cumulative-return series from periodic returns.

        Route: ``portfolio/cumulative_returns``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            returns: Per-period simple returns, oldest first (e.g. `0.01` for a `+1%` period).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'portfolio/cumulative_returns' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def drawdown(
        self,
        *,
        equity: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Per-step peak-to-trough drawdown series of an equity curve.

        Route: ``portfolio/drawdown``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            equity: Cumulative-return / equity levels, oldest first (e.g. `1.0, 1.1, 1.045`).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'portfolio/drawdown' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def max_drawdown(
        self,
        *,
        equity: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Worst drawdown magnitude over an equity curve, with peak/trough indices.

        Route: ``portfolio/max_drawdown``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            equity: Cumulative-return / equity levels, oldest first (e.g. `1.0, 1.1, 1.045`).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'portfolio/max_drawdown' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )
