# @generated by `cargo run -p xtask -- pysdk-sync` from the endpoint catalog.
# Do not edit by hand; regenerate and commit instead. Drift is gated by `pysdk-check`.

"""Generated ``quantitative`` router namespace for the FinX Platform SDK."""

from __future__ import annotations

from ._client import Client, FinXObject


class QuantitativeNamespace:
    """Accessor for the ``quantitative`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def calmar_ratio(
        self,
        *,
        **kwargs: object,
    ) -> FinXObject:
        """Calmar ratio: mean return over the absolute maximum drawdown.

        Route: ``quantitative/calmar_ratio``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.
        """
        raise NotImplementedError(
            "compute route 'quantitative/calmar_ratio' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def capm(
        self,
        *,
        risk_free_rate: float | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """CAPM alpha and beta of the asset returns versus a benchmark series.

        Route: ``quantitative/capm``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            risk_free_rate: Per-period risk-free rate subtracted from both the asset and benchmark returns before the regression (so alpha/beta are excess-return based).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'quantitative/capm' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def expected_shortfall(
        self,
        *,
        confidence: float | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Expected shortfall (conditional VaR): mean loss beyond the VaR cutoff.

        Route: ``quantitative/expected_shortfall``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            confidence: Confidence level in `(0, 1)`; the `VaR` quantile is the `1 − confidence` left-tail of the return distribution.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'quantitative/expected_shortfall' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def jarque_bera(
        self,
        *,
        **kwargs: object,
    ) -> FinXObject:
        """Jarque-Bera normality statistic and its chi-squared p-value.

        Route: ``quantitative/jarque_bera``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.
        """
        raise NotImplementedError(
            "compute route 'quantitative/jarque_bera' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def kurtosis(
        self,
        *,
        **kwargs: object,
    ) -> FinXObject:
        """Bias-corrected sample excess kurtosis of the returns.

        Route: ``quantitative/kurtosis``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.
        """
        raise NotImplementedError(
            "compute route 'quantitative/kurtosis' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def max_drawdown(
        self,
        *,
        **kwargs: object,
    ) -> FinXObject:
        """Maximum peak-to-trough drawdown (and the derived Calmar ratio).

        Route: ``quantitative/max_drawdown``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.
        """
        raise NotImplementedError(
            "compute route 'quantitative/max_drawdown' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def omega_ratio(
        self,
        *,
        threshold: float | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Omega ratio: gains-above-threshold over losses-below-threshold mass.

        Route: ``quantitative/omega_ratio``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            threshold: Threshold return separating gains (above) from losses (below).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'quantitative/omega_ratio' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def sharpe_ratio(
        self,
        *,
        periods: float | None = None,
        risk_free_rate: float | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Sharpe ratio of a returns series (rf, annualization periods).

        Route: ``quantitative/sharpe_ratio``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            periods: Annualization factor: the number of return periods per year (`252` daily, `12` monthly, `1` already annual). Must be `> 0`.
            risk_free_rate: Per-period risk-free rate subtracted from each return (the excess-return baseline).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'quantitative/sharpe_ratio' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def skewness(
        self,
        *,
        **kwargs: object,
    ) -> FinXObject:
        """Adjusted Fisher-Pearson sample skewness of the returns.

        Route: ``quantitative/skewness``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.
        """
        raise NotImplementedError(
            "compute route 'quantitative/skewness' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def sortino_ratio(
        self,
        *,
        periods: float | None = None,
        risk_free_rate: float | None = None,
        target_return: float | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Sortino ratio: excess return over downside deviation below a target.

        Route: ``quantitative/sortino_ratio``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            periods: Annualization factor (periods per year). Must be `> 0`.
            risk_free_rate: Per-period risk-free rate subtracted from each return.
            target_return: Minimum acceptable per-period return; only returns below this contribute to the downside-deviation denominator.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'quantitative/sortino_ratio' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def value_at_risk(
        self,
        *,
        confidence: float | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Historical Value-at-Risk at the given confidence level.

        Route: ``quantitative/value_at_risk``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            confidence: Confidence level in `(0, 1)`; the `VaR` quantile is the `1 − confidence` left-tail of the return distribution.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'quantitative/value_at_risk' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def volatility(
        self,
        *,
        periods: float | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Annualized volatility (standard deviation of returns scaled by periods).

        Route: ``quantitative/volatility``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            periods: Annualization factor (periods per year). Must be `> 0`.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'quantitative/volatility' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )
