# @generated by `cargo run -p xtask -- pysdk-sync` from the endpoint catalog.
# Do not edit by hand; regenerate and commit instead. Drift is gated by `pysdk-check`.

"""Generated ``regulators`` router namespace for the FinX Platform SDK."""

from __future__ import annotations

from ._client import Client, FinXObject


class RegulatorsFedNamespace:
    """Accessor for the ``regulators/fed`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def fomc_documents(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """FOMC meeting documents index from the Federal Reserve (keyless).

        Route: ``regulators/fed/fomc_documents``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("regulators/fed/fomc_documents", params)

class RegulatorsSecNamespace:
    """Accessor for the ``regulators/sec`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def cik_map(
        self,
        *,
        end_date: str | None = None,
        interval: str | None = None,
        limit: int | None = None,
        period: str | None = None,
        start_date: str | None = None,
        provider: str | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Map ticker symbols to SEC CIKs via SEC company_tickers.json (keyless).

        Route: ``regulators/sec/cik_map``.

        Args:
            end_date: Inclusive upper date bound, if the caller supplied one.
            interval: Bar / observation frequency (defaults to one day).
            limit: Caller-requested row cap, bounded by [`MAX_LIMIT`].
            period: Reporting cadence for fundamentals-style endpoints, if relevant.
            start_date: Inclusive lower date bound, if the caller supplied one.
            provider: Explicit provider key; ``None`` uses the catalog fallback order.
            **kwargs: Provider-specific arguments (e.g. ``symbol``) threaded to the query.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        params: dict[str, object] = dict(kwargs)
        if end_date is not None:
            params["end_date"] = end_date
        if interval is not None:
            params["interval"] = interval
        if limit is not None:
            params["limit"] = limit
        if period is not None:
            params["period"] = period
        if start_date is not None:
            params["start_date"] = start_date
        if provider is not None:
            params["provider"] = provider
        return self._client.fetch("regulators/sec/cik_map", params)

class RegulatorsNamespace:
    """Accessor for the ``regulators`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client
        self.fed = RegulatorsFedNamespace(client)
        self.sec = RegulatorsSecNamespace(client)

    # (no terminal routes at this namespace level)
