# @generated by `cargo run -p xtask -- pysdk-sync` from the endpoint catalog.
# Do not edit by hand; regenerate and commit instead. Drift is gated by `pysdk-check`.

"""Generated ``technical`` router namespace for the FinX Platform SDK."""

from __future__ import annotations

from ._client import Client, FinXObject


class TechnicalNamespace:
    """Accessor for the ``technical`` route namespace."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def ad(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Chaikin Accumulation/Distribution line.

        Route: ``technical/ad``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: Lookback window in bars.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/ad' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def adosc(
        self,
        *,
        fast: int | None = None,
        slow: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Chaikin Accumulation/Distribution Oscillator (EMA fast - EMA slow of A/D).

        Route: ``technical/adosc``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            fast: Fast EMA span over the A/D line.
            slow: Slow EMA span over the A/D line.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/adosc' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def adx(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Wilder ADX with +DI and -DI directional lines.

        Route: ``technical/adx``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: Wilder smoothing window for DM and TR.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/adx' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def aroon(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Aroon up, down, and oscillator.

        Route: ``technical/aroon``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: Lookback for the most-recent high/low extreme.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/aroon' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def atr(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Wilder Average True Range over the OHLC series.

        Route: ``technical/atr``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: Lookback window in bars.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/atr' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def bbands(
        self,
        *,
        length: int | None = None,
        std: float | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Bollinger Bands (upper/middle/lower).

        Route: ``technical/bbands``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: SMA / standard-deviation window.
            std: Number of standard deviations for the upper/lower band.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/bbands' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def cci(
        self,
        *,
        constant: float | None = None,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Commodity Channel Index over the typical price.

        Route: ``technical/cci``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            constant: Lambert scaling constant (0.015 by convention).
            length: Typical-price SMA window.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/cci' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def donchian(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Donchian Channels (rolling high/low extremes).

        Route: ``technical/donchian``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: Lookback window for the rolling high and low.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/donchian' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def ema(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Exponential moving average (SMA-seeded) over the close series.

        Route: ``technical/ema``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: Lookback window in bars.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/ema' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def fisher(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Ehlers Fisher transform with trigger line.

        Route: ``technical/fisher``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: High/low normalisation window.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/fisher' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def hma(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Hull moving average over the close series.

        Route: ``technical/hma``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: WMA window for the Hull moving average.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/hma' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def ichimoku(
        self,
        *,
        base: int | None = None,
        conversion: int | None = None,
        lagging: int | None = None,
        span_b: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Ichimoku Cloud (conversion, base, leading spans A/B, lagging span).

        Route: ``technical/ichimoku``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            base: Base-line (kijun-sen) window.
            conversion: Conversion-line (tenkan-sen) window.
            lagging: Lagging-span (chikou) back-shift in bars.
            span_b: Senkou span-B window.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/ichimoku' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def keltner(
        self,
        *,
        atr_length: int | None = None,
        length: int | None = None,
        multiplier: float | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Keltner Channels (EMA midline ± ATR multiple).

        Route: ``technical/keltner``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            atr_length: ATR window for the channel width.
            length: EMA window for the channel midline.
            multiplier: ATR multiplier for the upper/lower band.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/keltner' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def macd(
        self,
        *,
        fast: int | None = None,
        signal: int | None = None,
        slow: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """MACD line, signal, and histogram (12/26/9 defaults).

        Route: ``technical/macd``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            fast: Fast EMA span.
            signal: Signal EMA span (applied to the MACD line).
            slow: Slow EMA span.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/macd' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def momentum(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Momentum (price difference) over the close series.

        Route: ``technical/momentum``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: Number of bars to look back for the prior price.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/momentum' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def obv(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """On-Balance Volume running total.

        Route: ``technical/obv``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: Lookback window in bars.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/obv' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def roc(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Rate of change (percent) over the close series.

        Route: ``technical/roc``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: Number of bars to look back for the prior price.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/roc' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def rsi(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Wilder Relative Strength Index over the close series.

        Route: ``technical/rsi``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: Lookback window in bars.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/rsi' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def sma(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Simple moving average over the close series.

        Route: ``technical/sma``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: Lookback window in bars.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/sma' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def stochastic(
        self,
        *,
        d_period: int | None = None,
        k_period: int | None = None,
        k_smooth: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Stochastic oscillator %K and %D.

        Route: ``technical/stochastic``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            d_period: `%D` window (SMA of the smoothed `%K`).
            k_period: `%K` lookback window (high/low range).
            k_smooth: `%K` smoothing window (the slow `%K` SMA).

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/stochastic' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def supertrend(
        self,
        *,
        length: int | None = None,
        multiplier: float | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """SuperTrend ATR trailing-stop line and trend direction.

        Route: ``technical/supertrend``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: ATR window for the band half-width.
            multiplier: ATR multiplier for the upper/lower bands.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/supertrend' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def vortex(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Vortex Indicator (VI+ and VI- directional movement lines).

        Route: ``technical/vortex``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: Lookback window in bars.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/vortex' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def vwap(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Session-anchored Volume-Weighted Average Price.

        Route: ``technical/vwap``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: Lookback window in bars.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/vwap' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def wma(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Linearly weighted moving average over the close series.

        Route: ``technical/wma``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: Lookback window in bars.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/wma' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )

    def zlma(
        self,
        *,
        length: int | None = None,
        **kwargs: object,
    ) -> FinXObject:
        """Zero-Lag Exponential Moving Average over the close series.

        Route: ``technical/zlma``.

        This is a compute route, not served by the REST surface; calling it raises
        ``NotImplementedError``.

        Args:
            length: Lookback window in bars.

        Returns:
            A :class:`FinXObject` wrapping the result envelope.
        """
        raise NotImplementedError(
            "compute route 'technical/zlma' is not exposed over REST; "
            "use the MCP tool surface or the daemon Op::FetchData compute path"
        )
