[package]
name = "tdw-config"
version = "0.1.0"
edition = "2024"
publish = false
license = "UNLICENSED"

[dependencies]
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
