[package]
name = "tdw-cli"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
serde_json = { workspace = true }
tdw-config = { workspace = true }
tdw-protocol = { workspace = true }
tdw-service-api = { path = "../tdw-service-api" }
tdw-test-utils = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "io-util", "time"] }

[lints]
workspace = true
