// This file is @generated by prost-build from `proto/market_data.proto`.
//
// It is vendored (committed) rather than regenerated at build time so the crate
// builds with no system `protoc` and no build-time codegen dependency. To
// regenerate after editing the .proto: install `protoc`, run prost-build over
// `proto/market_data.proto`, and copy the output here verbatim.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OhlcvBar {
    /// e.g. "AAPL", "BTC-USD"
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    /// e.g. "polygon", "binance"
    #[prost(string, tag = "2")]
    pub provider: ::prost::alloc::string::String,
    /// e.g. "1m", "5m", "1h", "1d"
    #[prost(string, tag = "3")]
    pub timeframe: ::prost::alloc::string::String,
    /// bar open time, nanoseconds since Unix epoch (UTC)
    #[prost(int64, tag = "4")]
    pub ts_ns: i64,
    #[prost(double, tag = "5")]
    pub open: f64,
    #[prost(double, tag = "6")]
    pub high: f64,
    #[prost(double, tag = "7")]
    pub low: f64,
    #[prost(double, tag = "8")]
    pub close: f64,
    #[prost(double, tag = "9")]
    pub volume: f64,
    /// volume-weighted average (0 = not provided)
    #[prost(double, tag = "10")]
    pub vwap: f64,
    #[prost(uint64, tag = "11")]
    pub trade_count: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tick {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub provider: ::prost::alloc::string::String,
    /// nanoseconds since Unix epoch (UTC)
    #[prost(int64, tag = "3")]
    pub ts_ns: i64,
    #[prost(double, tag = "4")]
    pub price: f64,
    #[prost(double, tag = "5")]
    pub size: f64,
    #[prost(enumeration = "TradeSide", tag = "6")]
    pub side: i32,
    /// exchange-assigned trade ID (empty if not provided)
    #[prost(string, tag = "7")]
    pub trade_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PriceLevel {
    #[prost(double, tag = "1")]
    pub price: f64,
    #[prost(double, tag = "2")]
    pub quantity: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderBookSnapshot {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub provider: ::prost::alloc::string::String,
    /// nanoseconds since Unix epoch (UTC)
    #[prost(int64, tag = "3")]
    pub ts_ns: i64,
    #[prost(message, repeated, tag = "4")]
    pub bids: ::prost::alloc::vec::Vec<PriceLevel>,
    #[prost(message, repeated, tag = "5")]
    pub asks: ::prost::alloc::vec::Vec<PriceLevel>,
    /// exchange sequence number for ordering
    #[prost(uint64, tag = "6")]
    pub sequence: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketDataEnvelope {
    #[prost(string, tag = "1")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub symbol: ::prost::alloc::string::String,
    /// ULID of the ingest op
    #[prost(string, tag = "3")]
    pub ingestion_id: ::prost::alloc::string::String,
    /// nanoseconds since Unix epoch (UTC)
    #[prost(int64, tag = "4")]
    pub received_at_ns: i64,
    #[prost(oneof = "market_data_envelope::Payload", tags = "10, 11, 12")]
    pub payload: ::core::option::Option<market_data_envelope::Payload>,
}
/// Nested message and enum types in `MarketDataEnvelope`.
pub mod market_data_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "10")]
        Bar(super::OhlcvBar),
        #[prost(message, tag = "11")]
        Tick(super::Tick),
        #[prost(message, tag = "12")]
        OrderBook(super::OrderBookSnapshot),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TradeSide {
    Unknown = 0,
    Buy = 1,
    Sell = 2,
}
impl TradeSide {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "TRADE_SIDE_UNKNOWN",
            Self::Buy => "TRADE_SIDE_BUY",
            Self::Sell => "TRADE_SIDE_SELL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRADE_SIDE_UNKNOWN" => Some(Self::Unknown),
            "TRADE_SIDE_BUY" => Some(Self::Buy),
            "TRADE_SIDE_SELL" => Some(Self::Sell),
            _ => None,
        }
    }
}
